### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by 13821555741** [polison/JadaDynastyServer#1]
Hello, how to use this source code

**Comment by polison** [comment]
Just a test, develepment by yourself. 
Install Vusial Studio 2019 + .Net Core 5 + MySql.
Clone this code, import mysql from file.

**Comment by 13821555741** [comment]
Do you have Chinese software QQ？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "polison/JadaDynastyServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月6日(星期天) 上午9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [polison/JadaDynastyServer] consult (Issue #1)





 
Just a test, develepment by yourself.
 Install Vusial Studio 2019 + .Net Core 5 + MySql.
 Clone this code, import mysql from file.
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 13821555741** [comment]
I am a game enthusiast and don't understand the source code. Please give me some guidance

**Comment by 13821555741** [comment]
Hello, can't this enter the game？

**Comment by polison** [comment]
> 
Can't enter game.
Only can Create/Delete/Restore Character.

**Comment by 13821555741** [comment]
Friend, do you have chat software? Add a friend and let's talk
